source("R/build_graph.R")
g <- build_course_graph("data/courses_info.csv", "data/prereq_edges.csv")
check_dag(g)
write.csv(rank_key_courses(g), "data/key_courses.csv", row.names = FALSE)
saveRDS(g, "data/graph_object.rds")
